### ISSUE TITLE
Same Problem as #4

### ISSUE THREAD

**Issue by usdogu** [themayankjha/JAKYM#10] opened 2021-04-05 08:47 UTC
I installed simpleaudio and runned jakytm without python -m but problem still persist. you can check [this](https://asciinema.org/a/405175) for reference.

**Comment by themayankjha** [comment] 2021-04-05 13:44
Hello, I think this is an unintended bug. I am able to reproduce it. I will add it to the bug fixing list for the next patch.

Can you also check if it occurs if you exit after queuing music? 
Thank You for making jakym better!

**Comment by usdogu** [comment] 2021-04-06 05:48
> Can you also check if it occurs if you exit after queuing music?
yes

**Comment by themayankjha** [comment] 2021-04-06 08:35
The bug has been fixed it should behave as intended. Closing the issue.

**Closed by themayankjha** 2021-04-06 08:35 UTC
Labels: bug
